"use strict";
const STORAGE_PREFIX="simulador_certificacao_v3:";const LETTERS=["a","b","c","d","e"];
let sourceQuestions=[],questions=[],currentQuestion=0,userAnswers=[],imageMap=new Map(),timerSeconds=0,timerInterval=null,currentCsvFingerprint="",pendingSavedProgress=null,currentSettings=null;
const $=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",()=>{bindEvents()});
function bindEvents(){
 $("csvFile").addEventListener("change",handleCsvChanged);$("imageFolder").addEventListener("change",()=>{buildImageMap();setStatus(`${imageMap.size} imagem(ns) localizada(s).`,false,true)});
 $("startBtn").onclick=startNewSimulation;$("resumeBtn").onclick=resumeSimulation;$("clearSavedBtn").onclick=clearSaved;
 $("prevBtn").onclick=previousQuestion;$("nextBtn").onclick=nextQuestion;$("saveAndExitBtn").onclick=saveAndExit;
 $("showOnlyErrors").onclick=showOnlyErrors;$("showAllReview").onclick=showAllReview;$("restartBtn").onclick=restartApplication;
 $("closeImageModal").onclick=closeImageModal;$("imageModal").onclick=e=>{if(e.target===$("imageModal"))closeImageModal()};
 window.addEventListener("beforeunload",()=>{if(!$("quizScreen").classList.contains("hidden"))saveProgress()});
}
async function handleCsvChanged(){resetResumeUI();const file=$("csvFile").files[0];if(!file)return;showLoading(true,"Lendo CSV...");try{currentCsvFingerprint=`${file.name}:${file.size}:${file.lastModified}`;sourceQuestions=await parseCsv(file);pendingSavedProgress=loadSaved(currentCsvFingerprint);setStatus(`${sourceQuestions.length} questões carregadas.`,false,true);if(pendingSavedProgress)showResumeUI(pendingSavedProgress)}catch(e){setStatus(e.message||"Erro ao ler CSV.",true)}finally{showLoading(false)}}
function parseCsv(file){return new Promise((resolve,reject)=>{Papa.parse(file,{header:true,skipEmptyLines:"greedy",encoding:"UTF-8",transformHeader:h=>String(h||"").replace(/^\uFEFF/,"").trim().toLowerCase(),complete:r=>{const list=r.data.map((row,i)=>normalizeQuestion(row,i)).filter(q=>q.pergunta);if(!list.length)reject(new Error("CSV sem questões válidas."));else resolve(list)},error:()=>reject(new Error("Erro ao importar CSV."))})})}
function normalizeQuestion(row,index){const q={};Object.entries(row).forEach(([k,v])=>q[String(k).trim().toLowerCase()]=typeof v==="string"?v.trim():v);q.__key=q.id?`id:${q.id}`:`row:${index}:${String(q.pergunta||"").slice(0,80)}`;q.tipo=["multiple","multipla","múltipla","multi"].includes(String(q.tipo||"").toLowerCase())?"multiple":"single";q.correta=normalizeCorrect(q.correta).join(",");return q}
function buildImageMap(){revokeUrls();imageMap=new Map();for(const file of $("imageFolder").files){const url=URL.createObjectURL(file);const full=normImage(file.webkitRelativePath||file.name),name=normImage(file.name);imageMap.set(full,url);imageMap.set(name,url)}}
function normImage(v){return String(v||"").trim().replace(/\\/g,"/").replace(/^\.?\//,"").toLowerCase()}
function imageUrl(v){const n=normImage(v);if(!n)return"";return imageMap.get(n)||imageMap.get(n.split("/").pop())||""}
function revokeUrls(){new Set(imageMap.values()).forEach(u=>{if(String(u).startsWith("blob:"))URL.revokeObjectURL(u)})}
function validate(){if(!sourceQuestions.length){setStatus("Selecione um CSV válido.",true);return false}return true}
function readSettings(){const lim=Math.max(1,Math.min(parseInt($("questionLimit").value)||sourceQuestions.length,sourceQuestions.length));return{questionLimit:lim,timeLimitMinutes:Math.max(0,parseInt($("timeLimit").value)||0),shuffleQuestions:$("shuffleQuestions").checked,showUnansweredWarning:$("showUnansweredWarning").checked}}
function startNewSimulation(){if(!validate())return;showLoading(true,"Preparando...");buildImageMap();currentSettings=readSettings();questions=[...sourceQuestions];if(currentSettings.shuffleQuestions)shuffle(questions);questions=questions.slice(0,currentSettings.questionLimit);currentQuestion=0;userAnswers=Array.from({length:questions.length},()=>[]);timerSeconds=0;saveProgress();openQuiz();showLoading(false)}
function resumeSimulation(){if(!validate()||!pendingSavedProgress)return;showLoading(true,"Restaurando...");buildImageMap();const map=new Map(sourceQuestions.map(q=>[q.__key,q]));questions=pendingSavedProgress.questionKeys.map(k=>map.get(k)).filter(Boolean);userAnswers=Array.from({length:questions.length},(_,i)=>Array.isArray(pendingSavedProgress.userAnswers?.[i])?pendingSavedProgress.userAnswers[i]:[]);currentQuestion=Math.min(Math.max(pendingSavedProgress.currentQuestion||0,0),questions.length-1);timerSeconds=pendingSavedProgress.timerSeconds||0;currentSettings=pendingSavedProgress.settings||readSettings();openQuiz();showLoading(false)}
function openQuiz(){$("setupScreen").classList.add("hidden");$("resultScreen").classList.add("hidden");$("quizScreen").classList.remove("hidden");$("totalQuestions").textContent=questions.length;updateTimer();renderQuestion();startTimer();window.scrollTo({top:0})}
function startTimer(){stopTimer();timerInterval=setInterval(()=>{timerSeconds++;updateTimer();const max=(currentSettings?.timeLimitMinutes||0)*60;if(max&&timerSeconds>=max){stopTimer();alert("Tempo encerrado.");finishQuiz(true)}else if(timerSeconds%5===0)saveProgress()},1000)}
function stopTimer(){if(timerInterval!==null){clearInterval(timerInterval);timerInterval=null}}
function updateTimer(){$("timer").textContent=formatTime(timerSeconds)}
function formatTime(s){const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return(h?[h,m,sec]:[m,sec]).map(v=>String(v).padStart(2,"0")).join(":")}
function renderQuestion(){const q=questions[currentQuestion];if(!q)return;$("currentQuestion").textContent=currentQuestion+1;$("answeredCount").textContent=userAnswers.filter(a=>a.length).length;$("progressBar").style.width=`${(currentQuestion+1)/questions.length*100}%`;$("questionCategory").textContent=q.categoria||"";$("questionCategory").classList.toggle("hidden",!q.categoria);$("questionTypeBadge").textContent=q.tipo==="multiple"?"Múltiplas respostas":"Resposta única";$("multipleAlert").classList.toggle("hidden",q.tipo!=="multiple");$("questionText").textContent=q.pergunta||"";renderQuestionImage(q);renderOptions(q);$("prevBtn").disabled=currentQuestion===0;$("nextBtn").textContent=currentQuestion===questions.length-1?"Finalizar simulado":"Próxima →";saveProgress()}
function renderQuestionImage(q){const url=imageUrl(q.imagem_pergunta),wrap=$("questionImageWrapper"),img=$("questionImage");if(!url){wrap.classList.add("hidden");return}img.src=url;img.onclick=()=>openImageModal(url);wrap.classList.remove("hidden")}
function renderOptions(q){const c=$("optionsContainer"),saved=userAnswers[currentQuestion]||[];c.innerHTML="";LETTERS.forEach(l=>{const text=q[`alt_${l}`],im=q[`img_${l}`];if(!text&&!im)return;const L=l.toUpperCase(),label=document.createElement("label");label.className="option"+(saved.includes(L)?" selected":"");const input=document.createElement("input");input.type=q.tipo==="multiple"?"checkbox":"radio";input.name=`q-${currentQuestion}`;input.checked=saved.includes(L);input.onchange=()=>saveAnswer(L,q.tipo);const content=document.createElement("div");content.className="option-content";const tb=document.createElement("div");tb.className="option-text";tb.innerHTML=`<span class="option-letter">${L})</span>`;tb.appendChild(document.createTextNode(text||""));content.appendChild(tb);const url=imageUrl(im);if(url){const scroll=document.createElement("div");scroll.className="option-image-scroll";const img=document.createElement("img");img.className="option-image";img.src=url;img.onclick=e=>{e.preventDefault();e.stopPropagation();openImageModal(url)};scroll.appendChild(img);content.appendChild(scroll)}label.append(input,content);c.appendChild(label)})}
function saveAnswer(a,type){let arr=[...(userAnswers[currentQuestion]||[])];if(type==="multiple"){arr=arr.includes(a)?arr.filter(x=>x!==a):[...arr,a];userAnswers[currentQuestion]=arr.sort()}else userAnswers[currentQuestion]=[a];renderQuestion()}
function previousQuestion(){if(currentQuestion>0){currentQuestion--;renderQuestion();window.scrollTo({top:0})}}
function nextQuestion(){if(currentQuestion<questions.length-1){currentQuestion++;renderQuestion();window.scrollTo({top:0})}else finishQuiz(false)}
function saveAndExit(){saveProgress();stopTimer();$("quizScreen").classList.add("hidden");$("setupScreen").classList.remove("hidden");pendingSavedProgress=loadSaved(currentCsvFingerprint);showResumeUI(pendingSavedProgress);setStatus("Progresso salvo. Reimporte o mesmo CSV e a pasta para continuar.",false,true);window.scrollTo({top:0})}
function storageKey(fp=currentCsvFingerprint){return STORAGE_PREFIX+fp}
function saveProgress(){if(!currentCsvFingerprint||!questions.length)return;localStorage.setItem(storageKey(),JSON.stringify({currentQuestion,userAnswers,timerSeconds,questionKeys:questions.map(q=>q.__key),settings:currentSettings,savedAt:new Date().toISOString()}))}
function loadSaved(fp){try{const r=localStorage.getItem(storageKey(fp));return r?JSON.parse(r):null}catch{return null}}
function clearSaved(){localStorage.removeItem(storageKey());pendingSavedProgress=null;resetResumeUI();setStatus("Progresso apagado.",false,true)}
function showResumeUI(p){const answered=(p.userAnswers||[]).filter(a=>Array.isArray(a)&&a.length).length;$("resumeDescription").textContent=`${answered} de ${p.questionKeys.length} respondidas. Última posição: questão ${(p.currentQuestion||0)+1}.`;$("resumeNotice").classList.remove("hidden");$("clearSavedBtn").classList.remove("hidden")}
function resetResumeUI(){$("resumeNotice").classList.add("hidden");$("clearSavedBtn").classList.add("hidden")}
function finishQuiz(force){const unanswered=userAnswers.filter(a=>!a.length).length;if(!force&&currentSettings?.showUnansweredWarning&&unanswered&&!confirm(`Ainda existem ${unanswered} não respondida(s). Finalizar?`))return;stopTimer();$("quizScreen").classList.add("hidden");$("resultScreen").classList.remove("hidden");$("resultTime").textContent=`Tempo: ${formatTime(timerSeconds)}`;calculateResults();localStorage.removeItem(storageKey());window.scrollTo({top:0})}
function calculateResults(){let correct=0;const rc=$("reviewContainer");rc.innerHTML="";questions.forEach((q,i)=>{const user=normalizeArray(userAnswers[i]),right=normalizeCorrect(q.correta),ok=equal(user,right);if(ok)correct++;rc.appendChild(reviewItem(q,i,user,right,ok))});$("correctCount").textContent=correct;$("wrongCount").textContent=questions.length-correct;$("scorePercent").textContent=`${Math.round(correct/questions.length*100)}%`;showOnlyErrors()}
function reviewItem(q,i,user,right,ok){const item=document.createElement("article");item.className=`review-item ${ok?"correct":"wrong"}`;item.dataset.result=ok?"correct":"wrong";item.innerHTML=`<h3>Questão ${i+1} — ${ok?"Correta":"Incorreta"}</h3><div class="review-question-text"></div><div class="user-answer">Sua resposta: ${user.length?user.join(", "):"Não respondida"}</div><div class="correct-answer">Resposta correta: ${right.join(", ")||"Não informada"}</div>`;item.querySelector(".review-question-text").textContent=q.pergunta||"";const f=document.createElement("div");if(q.feedback){f.className="feedback";f.textContent=q.feedback;item.appendChild(f)}return item}
function showOnlyErrors(){document.querySelectorAll(".review-item").forEach(i=>i.classList.toggle("hidden",i.dataset.result!=="wrong"))}
function showAllReview(){document.querySelectorAll(".review-item").forEach(i=>i.classList.remove("hidden"))}
function normalizeCorrect(v){return String(v||"").replace(/["']/g,"").toUpperCase().split(/[,\s;|/]+/).filter(x=>/^[A-E]$/.test(x)).sort()}
function normalizeArray(v){return(Array.isArray(v)?v:[]).map(x=>String(x).toUpperCase()).filter(x=>/^[A-E]$/.test(x)).sort()}
function equal(a,b){return a.length===b.length&&a.every((v,i)=>v===b[i])}
function openImageModal(url){$("modalImage").src=url;$("imageModal").classList.remove("hidden");document.body.style.overflow="hidden"}
function closeImageModal(){$("imageModal").classList.add("hidden");$("modalImage").removeAttribute("src");document.body.style.overflow=""}
function restartApplication(){stopTimer();$("resultScreen").classList.add("hidden");$("setupScreen").classList.remove("hidden");window.scrollTo({top:0})}
function showLoading(show,text="Carregando..."){$("loadingText").textContent=text;$("loadingOverlay").classList.toggle("hidden",!show)}
function setStatus(msg,error=false,success=false){const s=$("importStatus");s.textContent=msg;s.classList.toggle("error-message",error);s.classList.toggle("success-message",success&&!error)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
